name: build android

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: android 19
            android: 19
            arch: 1686
            clang_prefix: i686-linux-android
          - os: ubuntu-latest
            name: android 19
            android: 19
            arch: armv7a
            clang_prefix: armv7a-linux-androideabi
          - os: ubuntu-latest
            name: android 21
            android: 21
            arch: 1686
            clang_prefix: i686-linux-android
          - os: ubuntu-latest
            name: android 21
            android: 21
            arch: armv7a
            clang_prefix: armv7a-linux-androideabi
          - os: ubuntu-latest
            name: android 21
            android: 21
            arch: x86_64
            clang_prefix: x86_64-linux-android
          - os: ubuntu-latest
            name: android 21
            android: 21
            arch: aarch64
            clang_prefix: aarch64-linux-android

    runs-on: ${{ matrix.os }}

    name: build (${{ matrix.name }} @ ${{ matrix.arch }})

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: uncompress docker image
        run: |
          xz -d ./ubuntu.tar.xz

      - name: load docker image
        run: |
          sudo docker image load -i ./ubuntu.tar

      - name: create docker container
        run: |
          sudo docker container create --user ubuntu --workdir /home/ubuntu --init --tty --tmpfs /tmp --ulimit nofile=262144:262144 --name git_local_ubuntu git_local_ubuntu:23.10

      - name: start docker container
        run: |
          sudo docker container start git_local_ubuntu
      
      - name: allow ubuntu user to sudo
        run: |
          sudo docker container exec --user root git_local_ubuntu bash -c "echo 'ubuntu ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/ubuntu"

      - name: install perl readline
        run: |
          sudo docker container exec git_local_ubuntu bash -c "sudo apt install -y libterm-readline-gnu-perl"

      - name: generate program
        run: |
          sudo docker container exec git_local_ubuntu bash -c "printf \"#include <stdio.h>\nint main() { printf(\\\"hello\\\\\n\\\"); return 0; }\n\" > program.c"

      - name: cat program
        run: |
          sudo docker container exec git_local_ubuntu bash -c "cat program.c"

      - name: install NDK 25c
        run: |
          sudo docker container exec git_local_ubuntu bash -c "printf \"1\n\" | sudo apt install -y google-android-ndk-r25c-installer"

      # - name: Setup ssh session
      #   uses: mxschmitt/action-tmate@v3
      #   timeout-minutes: 50
        # sudo docker container exec -it git_local_ubuntu bash -i
      
      - name: compile program
        run: |
          sudo docker container exec git_local_ubuntu bash -c "/lib/android-sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/${{ matrix.clang_prefix }}${{ matrix.android }}-clang program.c -O3 -g0 -o program-android-${{ matrix.android }}-${{ matrix.arch }}"
      
      - name: copy program
        run: |
          sudo docker cp git_local_ubuntu:/home/ubuntu/program-android-${{ matrix.android }}-${{ matrix.arch }} ./program-android-${{ matrix.android }}-${{ matrix.arch }}

      - uses: actions/upload-artifact@v3
        with:
          name: program-android-${{ matrix.android }}-${{ matrix.arch }}
          path: 
          retention-days: 1
