name: build linux

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux

    runs-on: ${{ matrix.os }}
    
    name: build (${{ matrix.name }})
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: uncompress docker image
        run: |
          xz -d ./ubuntu.tar.xz

      - name: load docker image
        run: |
          sudo docker image load -i ./ubuntu.tar

      - name: create docker container
        run: |
          sudo docker container create --user ubuntu --workdir /home/ubuntu --init --tty --tmpfs /tmp --ulimit nofile=262144:262144 --name git_local_ubuntu git_local_ubuntu:23.10

      - name: start docker container
        run: |
          sudo docker container start git_local_ubuntu
      
      - name: allow ubuntu user to sudo
        run: |
          sudo docker container exec --user root git_local_ubuntu bash -c "echo 'ubuntu ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/ubuntu"

      - name: install perl readline
        run: |
          sudo docker container exec git_local_ubuntu bash -c "sudo apt install -y libterm-readline-gnu-perl"

      - name: generate program
        run: |
          sudo docker container exec git_local_ubuntu bash -c "printf \"#include <stdio.h>\nint main() { printf(\\\"hello\\\\\n\\\"); return 0; }\n\" > program.c"

      - name: cat program
        run: |
          sudo docker container exec git_local_ubuntu bash -c "cat program.c"

      - name: install clang
        run: |
          sudo docker container exec git_local_ubuntu bash -c "sudo apt install -y clang"

      - name: compile program
        run: |
          sudo docker container exec git_local_ubuntu bash -c "clang program.c -O3 -g0 -o program-linux"

      - name: execute program
        run: |
          sudo docker container exec git_local_ubuntu bash -c "./program-linux"

      - name: copy program
        run: |
          sudo docker cp git_local_ubuntu:/home/ubuntu/program-linux ./program-linux

      - uses: actions/upload-artifact@v3
        with:
          name: program-linux
          path: 
          retention-days: 1
