name: linux

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
            flatpack_id: org.flatpak.Hello

    runs-on: ${{ matrix.os }}
    
    name: ${{ matrix.name }}
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: uncompress docker image
        run: |
          xz -d ./ubuntu.tar.xz

      - name: load docker image
        run: |
          sudo docker image load -i ./ubuntu.tar

      - name: create docker container
        run: |
          sudo docker container create --user ubuntu --workdir /home/ubuntu --init --tty --tmpfs /tmp --ulimit nofile=262144:262144 --name git_local_ubuntu git_local_ubuntu:23.10

      - name: start docker container
        run: |
          sudo docker container start git_local_ubuntu
      
      - name: allow ubuntu user to sudo
        run: |
          sudo docker container exec --user root git_local_ubuntu bash -c "echo 'ubuntu ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/ubuntu"

      - name: install apt-utils
        run: |
          sudo docker container exec git_local_ubuntu bash -c "sudo apt install -y apt-utils"

      - name: install perl-readline
        run: |
          sudo docker container exec git_local_ubuntu bash -c "sudo apt install -y libterm-readline-gnu-perl"

      - name: install systemd
        run: |
          sudo docker container exec git_local_ubuntu bash -c "sudo apt install -y systemd systemd-sysv systemd-dev"

      - name: boot systemd - commit image
        run: |
          sudo docker container commit git_local_ubuntu git_local_ubuntu:23.10

      - name: boot systemd - stop container
        run: |
          sudo docker container stop git_local_ubuntu

      - name: boot systemd - remove container
        run: |
          sudo docker container rm git_local_ubuntu

      - name: boot systemd - create systemd container inspect mount
        run: |
          sudo docker container create --user root --workdir /home/root --tmpfs /tmp --tty --cap-add SYS_ADMIN --privileged --security-opt apparmor:unconfined --ulimit nofile=262144:262144 -v /sys/fs/cgroup:/sys/fs/cgroup:rw --name git_local_ubuntu git_local_ubuntu:23.10 /bin/mount

      - name: boot systemd - start systemd container inspect mount
        run: |
          sudo docker container start git_local_ubuntu -i

      - name: boot systemd - start systemd container remove mount
        run: |
          sudo docker container stop git_local_ubuntu
          sudo docker container rm git_local_ubuntu

      - name: boot systemd - create systemd container
        run: |
          sudo docker container create --user root --workdir /home/root --tmpfs /tmp --tty --cap-add SYS_ADMIN --privileged --security-opt apparmor:unconfined --ulimit nofile=262144:262144 -v /sys/fs/cgroup:/sys/fs/cgroup:rw --name git_local_ubuntu git_local_ubuntu:23.10 /sbin/init

      - name: boot systemd - start systemd container
        run: |
          sudo docker container start git_local_ubuntu -i

      - name: boot systemd - verify
        run: |
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "systemctl status"

      - name: generate program
        run: |
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "printf \"#include <stdio.h>\nint main() { printf(\\\"Hello World!\\\\\n\\\"); return 0; }\n\" > program.c"

      - name: cat program
        run: |
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "cat program.c"

      - name: install clang
        run: |
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "sudo apt install -y clang"

      - name: compile program
        run: |
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "clang program.c -O3 -g0 -o program-linux"

      - name: execute program
        run: |
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "./program-linux"

      - name: copy program
        run: |
          sudo docker cp git_local_ubuntu:/home/ubuntu/program-linux ./program-linux

      - name: install flatpak
        run: |
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "sudo apt install -y flatpak"

      - name: add flatpak repository
        run: |
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo"

      - name: install flatpak builder
        run: |
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "flatpak install flathub org.flatpak.Builder"

      - name: install flatpak sdk
        run: |
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "flatpak install flathub org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08"

      - name: write flatpak manifest
        run: |
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "echo \"app-id: ${{ matrix.flatpak_id }}\" > ${{ matrix.flatpak_id }}.yml"
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "echo \"runtime: org.freedesktop.Platform\" >> ${{ matrix.flatpak_id }}.yml"
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "echo \"runtime-version: '23.08'\" >> ${{ matrix.flatpak_id }}.yml"
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "echo \"sdk: org.freedesktop.Sdk\" >> ${{ matrix.flatpak_id }}.yml"
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "echo \"command: program-linux\" >> ${{ matrix.flatpak_id }}.yml"
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "echo \"modules:\" >> ${{ matrix.flatpak_id }}.yml"
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "echo \"  - name: hello\" >> ${{ matrix.flatpak_id }}.yml"
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "echo \"    buildsystem: simple\" >> ${{ matrix.flatpak_id }}.yml"
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "echo \"    build-commands:\" >> ${{ matrix.flatpak_id }}.yml"
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "echo \"      - install -D program-linux /app/bin/program-linux\" >> ${{ matrix.flatpak_id }}.yml"
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "echo \"    sources:\" >> ${{ matrix.flatpak_id }}.yml"
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "echo \"      - type: file\" >> ${{ matrix.flatpak_id }}.yml"
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "echo \"      - path: program-linux\" >> ${{ matrix.flatpak_id }}.yml"
        
      - name: build flatpak package
        run: |
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "flatpak-builder build-dir ${{ matrix.flatpak_id }}.yml"

      - name: execute flatpak package - install
        run: |
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "flatpak-builder --user --install --force-clean build-dir ${{ matrix.flatpak_id }}.yml"

      - name: execute flatpak package - run
        run: |
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "flatpak run ${{ matrix.flatpak_id }}"

      - name: copy flatpak package - tar
        run: |
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "mkdir flatpak-package"
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "mv build-dir ${{ matrix.flatpak_id }}.yml flatpak-package"
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "echo "flatpak-builder --user --install build-dir ${{ matrix.flatpak_id }}.yml" > flatpak-package/install.sh"
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "echo "chmod +x flatpak-package/install.sh"
          sudo docker container exec --user ubuntu git_local_ubuntu bash -c "tar -cvf flatpak-package.tar flatpak-package"

      - name: copy flatpak package - copy
        run: |
          sudo docker cp git_local_ubuntu:/home/ubuntu/flatpak-package.tar ./flatpak-package.tar

      - uses: actions/upload-artifact@v3
        with:
          name: program-linux
          path: ./program-linux
          retention-days: 1

      - uses: actions/upload-artifact@v3
        with:
          name: flatpak-package.tar
          path: ./flatpak-package.tar
          retention-days: 1
