name: windows

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows

    runs-on: ${{ matrix.os }}
    
    name: ${{ matrix.name }}
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: TODO - BUILD ON WINDOWS
        run: echo TODO
