name: windows

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows

    runs-on: ${{ matrix.os }}
    
    name: ${{ matrix.name }}
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: generate program
        run: |
          bash -c "printf \"#include <stdio.h>\nint main() { printf(\\\"Hello World!\\\\\n\\\"); return 0; }\n\" > program.c"

      - name: cat program
        run: |
          cat program.c

      - name: compile program
        run: |
          clang program.c -O3 -g0 -o program-windows.exe

      - name: execute program
        run: |
          ./program-windows.exe

      - uses: actions/upload-artifact@v3
        with:
          name: program-windows.exe
          path: ./program-windows.exe
          retention-days: 1
